=== artfisica/opendata.cern.ch/cernopendata/jsonschemas/records/glossary-term-v1.0.0.json
{
	  "$schema": "http://json-schema.org/draft-04/schema#",
	  "description": "Describe information needed for glossary term entity.",
	  "properties": {
		    "id": {
            "type": "string",
            "title": "id"
        },
        "type": {
            "type": "object",
            "properties": {
                "primary": {
                    "type": "string"
                },
                "secondary": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            }
        },
        "term": {
			      "type": "array",
            "title": "Term",
            "items": {
                "type": "string"
            }
		    },
		    "anchor": {
			      "type": "string",
            "title": "Anchor"
		    },
		    "category": {
			      "type": "string",
            "title": "Category"
		    },
		    "definition": {
			      "type": "string",
            "title": "Definition"
		    },
		    "experiment": {
			      "type": "array",
            "title": "Experiment",
			      "items": {
				        "type": "object",
				        "properties": {
					          "name": {
						            "title": "Name",
						            "type": "string"
					          }
				        }
			      }
		    },
		    "see_also": {
			      "type": "array",
            "title": "See also",
			      "items": {
				        "type": "object",
				        "properties": {
					          "term": {
						            "title": "Term",
						            "type": "string"
					          }
				        }
			      }
		    },
		    "links": {
            "title": "Links",
			      "type": "array",
			      "items": {
				        "type": "object",
				        "properties": {
					          "text": {
						            "title": "Text",
						            "type": "string"
					          },
					          "url": {
						            "title": "Url",
						            "type": "string"
					          }
				        }
			      }
		    }

	  },
	  "title": "Glossary Term Schema.",
	  "type": "object"
}

=== artfisica/opendata.cern.ch/cernopendata/modules/fixtures/data/terms/terms.json
[
  {
    "anchor": "AOD",
    "category": "specific",
    "definition": "Stands for \u201cAnalysis Object Data\u201d, a format that contains all information needed for a CMS analysis. It contains reconstructed \u201cphysics objects\u201d such as electrons, photons and muons.",
    "experiment": [
      {
        "name": "CMS"
      }
    ],
    "links": [
      {
        "text": "Read more in the CMS WorkBook",
        "url": "https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookDataFormats#AoD"
      },
      {
        "text": "Read more on the \u201cAbout CMS\u201d page on this portal",
        "url": "http://opendata.cern.ch/about/CMS"
      }
    ],
    "see_also": [
      {
        "term": "primary"
      },
      {
        "term": "reconstruction"
      },
      {
        "term": "tag"
      }
    ],
    "term": [
      "AOD"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "CMSSW",
    "category": "specific",
    "definition": "Stands for CMS Software and refers to (1) the so-called \u201cOffline\u201d software needed to simulate, reconstruct and analyse CMS data, and (2) the \u201cOnline\u201d software needed for data selection and storage.",
    "experiment": [
      {
        "name": "CMS"
      }
    ],
    "links": [
      {
        "text": "See the CMSSW codebase on GitHub",
        "url": "https://github.com/cms-sw/cmssw"
      }
    ],
    "see_also": [
      {
        "term": "PAT"
      }
    ],
    "term": [
      "CMSSW"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "derived",
    "category": "specific",
    "definition": "Contains data that have been derived from the primary datasets. The data may be reduced in the sense that (a) only part of the information is kept or (b) only part of the events are selected.",
    "experiment": [
      {
        "name": "CMS"
      },
      {
        "name": "ATLAS"
      },
      {
        "name": "ALICE"
      },
      {
        "name": "LHCb"
      }
    ],
    "links": [
      {
        "text": "See all the \u201cDerived datasets\u201d collections on this portal",
        "url": "http://opendata.cern.ch/search?ln=en&p=+%28collection%3AALICE-Derived-Datasets+OR+collection%3ACMS-Derived-Datasets+OR+collection%3AATLAS-Derived-Datasets+OR+collection%3ALHCb-Derived-Datasets%29&action_search="
      }
    ],
    "see_also": [
      {
        "term": "primary"
      },
      {
        "term": "tag"
      },
      {
        "term": "condition"
      }
    ],
    "term": [
      "Derived Dataset",
      "Derived Datasets"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "electron",
    "category": "generic",
    "definition": "A stable elementary particle belonging to the first generation of the \u201clepton\u201d family of particles. It has a $-$1 electrical charge, while its anti-particle, the anti-electron or positron, has a +1 electrical charge. Atoms are made of electrons orbiting positively charged nuclei. An electron has a mass of ~0.5 MeV/c$^2$, or about 1/1836 times the mass of a proton.",
    "links": [
      {
        "text": "Read more on Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Electron"
      }
    ],
    "see_also": [
      {
        "term": "muon"
      },
      {
        "term": "proton"
      },
      {
        "term": "neutrino"
      }
    ],
    "term": [
      "Electron",
      "Electrons"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "generator",
    "category": "generic",
    "definition": "Simulation programs used to generate particle collisions.",
    "links": [
      {
        "text": "Read more on Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Event_generator"
      }
    ],
    "see_also": [
      {
        "term": "montecarlo"
      },
      {
        "term": "primary"
      },
      {
        "term": "derived"
      },
      {
        "term": "condition"
      }
    ],
    "term": [
      "Event generator",
      "Event generators",
      "Generator",
      "Generators"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "tag",
    "category": "specific",
    "definition": "A Global Tag is a coherent collection of records of additional data needed by the reconstruction and analysis software. These records are stored in the Condition Database. Condition data include non-event-related information (Alignment, Calibration, Temperature, etc.) and parameters for the simulation/reconstruction/analysis software.",
    "experiment": [
      {
        "name": "CMS"
      }
    ],
    "links": [
      {
        "text": "Read more about CMS Global Tags",
        "url": "https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions"
      }
    ],
    "see_also": [
      {
        "term": "reconstruction"
      },
      {
        "term": "AOD"
      },
      {
        "term": "primary"
      }
    ],
    "term": [
      "Global Tag",
      "Global Tags",
      "Condition Data",
      "Condition Database"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "gluon",
    "category": "generic",
    "definition": "An elementary particle belonging to the \u201cboson\u201d family of particles. It is the carrier of the strong force that binds quarks together to form hadrons. It is massless and has no electrical charge but has a property known as \u201ccolour charge\u201d.",
    "links": [
      {
        "text": "Read more on Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Gluon"
      }
    ],
    "see_also": [
      {
        "term": "quark"
      },
      {
        "term": "photon"
      }
    ],
    "term": [
      "Gluon",
      "Gluons"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "hadron",
    "category": "generic",
    "definition": "A composite particle made of two or more quarks. There are two sub-categories of hadrons: \u201cbaryons\u201d such as protons and neutrons are made of three quarks (or three anti-quarks), while \u201cmesons\u201d are made of a quark and an anti-quark. Atomic nuclei can also be considered hadrons, since they are also fundamentally made of quarks. The LHC collides two species of hadrons: protons and lead nuclei (also called lead ions). Hadrons produced in collisions typically cluster together to form particle jets in the detectors.",
    "links": [
      {
        "text": "Read more on Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Hadron"
      }
    ],
    "see_also": [
      {
        "term": "proton"
      },
      {
        "term": "quark"
      },
      {
        "term": "jet"
      },
      {
        "term": "ion"
      }
    ],
    "term": [
      "Hadron",
      "Hadrons"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "ion",
    "category": "generic",
    "definition": "An ion is an atom or a molecule in which the number of electrons is not the same as the number of protons. In the context of the LHC, the term \u201cheavy ion\u201d refers to the nuclei of heavy atoms such as lead.",
    "links": [
      {
        "text": "Read more about heavy-ion physics on the CERN website",
        "url": "http://home.web.cern.ch/about/physics/heavy-ions-and-quark-gluon-plasma"
      }
    ],
    "see_also": [
      {
        "term": "proton"
      },
      {
        "term": "quark"
      },
      {
        "term": "jet"
      },
      {
        "term": "ion"
      }
    ],
    "term": [
      "Ion",
      "Ions"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "lumisection",
    "category": "specific",
    "definition": "A lumi section is a fixed time period in data taking, approximately 24 seconds.",
    "experiment": [
      {
        "name": "CMS"
      }
    ],
    "term": [
      "Lumi section",
      "lumisection"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "montecarlo",
    "category": "generic",
    "definition": "Refers to computational algorithms based on numerical random samplings that is used in simulation programs for generating the particle collisions and for simulating of particle interactions in the detector material. Often used as a synonym for simulated data.",
    "links": [
      {
        "text": "Read more on Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Monte_Carlo_method"
      }
    ],
    "see_also": [
      {
        "term": "generator"
      },
      {
        "term": "primary"
      },
      {
        "term": "derived"
      },
      {
        "term": "condition"
      }
    ],
    "term": [
      "Monte Carlo"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "muon",
    "category": "generic",
    "definition": "An elementary particle belonging to the second generation of the \u201clepton\u201d family of particles. It has a $-$1 electrical charge, while its anti-particle, the anti-muon, has a +1 electrical charge. A muon\u2019s properties are similar to those of an electron but it is around 200 times more massive. It is represented by the Greek letter \u201c$\\mu$\u201d.",
    "links": [
      {
        "text": "Read more on Wikipedia",
        "url": "https://en.wikipedia.org/wiki/Muon"
      }
    ],
    "see_also": [
      {
        "term": "electron"
      },
      {
        "term": "neutrino"
      }
    ],
    "term": [
      "Muon",
      "Muons"
    ],
    "type": {
      "primary": "Glossary"
    }
  },
  {
    "anchor": "neutrino",
    "category": "generic",
