=== artfisica/opendata.cern.ch/cernopendata/jsonschemas/records/record-v1.0.0.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "description": "Record",
  "properties": {
    "_files": {
      "items": {
        "properties": {
          "bucket": {
            "type": "string"
          },
          "checksum": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "key": {
            "type": "string"
          },
          "size": {
            "type": "integer"
          },
          "type": {
            "type": "string"
          },
          "uri": {
            "type": "string"
          },
          "version_id": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array",
      "uniqueItems": true
    },
    "abstract": {
      "properties": {
        "description": {
          "type": "string"
        },
        "links": {
          "items": {
            "properties": {
              "description": {
                "type": "string"
              },
              "recid": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "accelerator": {
      "type": "string"
    },
    "authors": {
      "items": {
        "properties": {
          "affiliation": {
            "type": "string"
          },
          "ccid": {
            "type": "string"
          },
          "inspireid": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "cms_confdb_id": {
      "type": "string"
    },
    "collaboration": {
      "properties": {
        "group": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "recid": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "collections": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "collision_information": {
      "properties": {
        "energy": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "dataset_semantics": {
      "items": {
        "properties": {
          "description": {
            "type": "string"
          },
          "variable": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "date_created": {
      "type": "string"
    },
    "date_published": {
      "type": "string"
    },
    "date_reprocessed": {
      "type": "string"
    },
    "distribution": {
      "properties": {
        "formats": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "number_events": {
          "type": "integer"
        },
        "number_files": {
          "type": "integer"
        },
        "size": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "doi": {
      "type": "string"
    },
    "experiment": {
      "type": "string"
    },
    "generator": {
      "properties": {
        "global_tag": {
          "type": "string"
        },
        "names": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "keywords": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "language": {
      "type": "string"
    },
    "license": {
      "properties": {
        "attribution": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "links": {
      "items": {
        "properties": {
          "description": {
            "type": "string"
          },
          "recid": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "methodology": {
      "properties": {
        "description": {
          "type": "string"
        },
        "links": {
          "items": {
            "properties": {
              "description": {
                "type": "string"
              },
              "recid": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "note": {
      "properties": {
        "description": {
          "type": "string"
        },
        "links": {
          "items": {
            "properties": {
              "description": {
                "type": "string"
              },
              "recid": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "pileup": {
      "properties": {
        "description": {
          "type": "string"
        },
        "links": {
          "items": {
            "properties": {
              "description": {
                "type": "string"
              },
              "recid": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "prepublication": {
      "properties": {
        "date": {
          "type": "string"
        },
        "place": {
          "type": "string"
        },
        "publisher": {
          "type": "string"
        },
        "report_number": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "publisher": {
      "type": "string"
    },
    "recid": {
      "type": "string"
    },
    "relations": {
      "items": {
        "properties": {
          "description": {
            "type": "string"
          },
          "doi": {
            "type": "string"
          },
          "recid": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "run_period": {
      "type": "string"
    },
    "system_details": {
      "properties": {
        "description": {
          "type": "string"
        },
        "global_tag": {
          "type": "string"
        },
        "recid": {
          "type": "string"
        },
        "release": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "title": {
      "type": "string"
    },
    "title_additional": {
      "type": "string"
    },
    "topic": {
      "properties": {
        "category": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "type": {
      "properties": {
        "primary": {
          "type": "string"
        },
        "secondary": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "usage": {
      "properties": {
        "description": {
          "type": "string"
        },
        "links": {
          "items": {
            "properties": {
              "description": {
                "type": "string"
              },
              "recid": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "use_with": {
      "properties": {
        "description": {
          "type": "string"
        },
        "links": {
          "items": {
            "properties": {
              "description": {
                "type": "string"
              },
              "recid": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "validation": {
      "properties": {
        "description": {
          "type": "string"
        },
        "links": {
          "items": {
            "properties": {
              "description": {
                "type": "string"
              },
              "recid": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    }
  },
  "type": "object"
}

=== artfisica/opendata.cern.ch/cernopendata/modules/fixtures/data/records/cms-condition-data-Run2010B.json
[
  {
    "abstract": {
      "description": "Condition database includes non-event-related\n      information (Alignment, Calibration, Temperature, etc) and parameters for\n      simulation/reconstruction/analysis software."
    },
    "accelerator": "CERN-LHC",
    "collaboration": {
      "name": "CMS collaboration",
      "recid": "450"
    },
    "collections": [
      "CMS-Condition-Data"
    ],
    "date_created": "2010",
    "date_published": "2016",
    "experiment": "CMS",
    "publisher": "CERN Open Data Portal",
    "recid": "1800",
    "run_period": "Run2010B",
    "title": "Condition data for 2010 CMS collision data",
    "type": {
      "primary": "Environment",
      "secondary": [
        "Condition"
      ]
    }
  }
]
